name: MusicMachine
description: A project for the Devathon contest
version: 1.0.0
author: Minikloon

main: org.devathon.contest2016.mm.MusicMachine

commands:
  supernote:
    description: Gives you a super note gun
    usage: /supernote